### ISSUE TITLE
Unable to Find Matching ArcGIS Installation

### ISSUE THREAD

**Issue by pmacMaps** [WSDOT-GIS/arcmap-spellcheck#2]
When I tried to run the add-in (10.3.1, Windows 7), I got the following message:

Unable to find a matching ArcGIS installation on this machine. Choose Yes to proceed with installation, choose No to cancel installation.

**Comment by JeffJacobson** [comment]
It was built using the 10.4.1 ArcObjects SDK. If you're using an earlier version of ArcMap, this could be the cause of the problem. (10.5 should work, though.) I've updated the README.md file with the required version.

If you actually are using 10.4.1 or higher, though, let me know. If you're using an earlier ArcMap version, you may be able to get the addin to work by compiling the source code on your own computer after changing the version number in the `.esriaddinx` file.

**Comment by pmacMaps** [comment]
Thanks for the info. After reading the help on adding add-in files, I wondered if it was built with a newer release than 10.3.1.  We'll be upgrading to 10.5 soon, so I'll just wait to install this.

**Comment by piyush4196** [comment]
I am getting the warning when i am trying to add addin in arcmap 10.6. I have written  the code for  ArcGIS 10.6.1 and trying to run in  10.7.1.  I just change the target version in the config.esriaddinx file: 

<Targets>
<Target name="Desktop" version="10.6" />
<Target name="Desktop" version="10.7" />
</Targets>

Addin is working fine in 10.7.1 but when i am trying to add addin in 10.6.1 i am getting the warning "Unable to find a matching arcgis installation on this machine" . 

Any help/suggestion will be highly appreciated.
